### PR TITLE
[Curated-Apps] Move to Gramine v1.6

### LINKED ISSUE #63: All Intel-Confidential-Compute-for-X workloads failing with meson version v1.3.0
Currently, All Confidential Compute workload is broken because of [https://github.com/gramineproject/gsc/issues/178](https://github.com/gramineproject/gsc/issues/178) because contrib uses gsc v1.5 and gramine v1.5

## Description
Recently meson version has been upgraded to v1.3.0, due to which gsc v1.5 build fails with error Cannot link_whole a custom or Rust target 'curl' into a static library 'sgx_util'.

Currently meson version has been restricted to meson>=0.56,!=1.2.*

### PR DESCRIPTION
**Pull request by jkr0103**
Currently Curated-Apps uses Gramine v1.5 version.

This PR move the Curated-Apps to use Gramine v1.6 version.

Fixes #63 

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/68#-Nlto2RJBrTyjbPB7t0F):*
"v" already means "version"



_Suggestion:_
```
[Curated-Apps] Move to Gramine v1.6
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)* status: all files reviewed, 1 unresolved discussion (waiting on @jkr0103)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/68#-Nlto2RJBrTyjbPB7t0F):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"v" already means "version"
</blockquote></details>

Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/68)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
