### PR TITLE
[Curated-Apps] Update Azure VM type for tensorflow-serving testing

### PR DESCRIPTION
**Pull request by sahason**
Signed-off-by: Sonali Saha <sonali.saha@intel.com>

Updated the type of Azure VM which was used for testing tensorflow-serving.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/27)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/27)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Curated-Apps/workloads/tensorflow-serving/README.md` line 48 at r1](https://reviewable.io/reviews/gramineproject/contrib/27#-NL-wcm29u_L88IIgRTV:-NL-wcm29u_L88IIgRTW:b-j3i1ep) ([raw file](https://github.com/gramineproject/contrib/blob/01dc7ce34f3e190ee69f93a6f52b8a54db2e0890/Curated-Apps/workloads/tensorflow-serving/README.md#L48)):*
> ```Markdown
> ## Run the confidential compute image for tensorflow-serving
> 
> - This example was tested on a Standard_DC48ds_v3 Azure VM.
> ```

In case anyone is curious what this machine is: https://learn.microsoft.com/en-us/azure/virtual-machines/dedicated-host-general-purpose-skus#dcdsv3-type1

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/27)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @sahason)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/27#-NLLYmrIABF03l-CbvDR):*
(it is bigger, right?)



_Suggestion:_
```
Change Azure VM type to a bigger instance
```
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/27#-NLLYhxuBPg2Z7JV2qS6):*
Please state the reason+context for the change

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/27)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/27#-NLLYmrIABF03l-CbvDR):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(it is bigger, right?)
</blockquote></details>

Done.
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/27#-NLLYhxuBPg2Z7JV2qS6):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please state the reason+context for the change
</blockquote></details>

The validation started with Azure VM instance Standard_DC8s_v3. So at the point of submitting this PR, this instance was mentioned. But later a bigger instance was arranged (Standard_DC48ds_v3) which was required for a 64 GB enclave. This has been missed to add.

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/27)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/27#-NLLYhxuBPg2Z7JV2qS6):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The validation started with Azure VM instance Standard_DC8s_v3. So at the point of submitting this PR, this instance was mentioned. But later a bigger instance was arranged (Standard_DC48ds_v3) which was required for a 64 GB enclave. This has been missed to add.
</blockquote></details>

I guess Michal wants this to be reflected in the commit message. So I'd write like this:
```
[Curated-Apps] Change Azure VM type to a bigger instance

Validation of TensorFlow Serving workload started on a small DC8s_v3 Azure VM
instance, which was put in the README. However, since TensorFlow Serving
requires large amount of EPC, final validation was done on a large DC48ds_v3
instance, which has sufficient EPC for a 64GB enclave. We forgot to update
the README with this info, so let's do it now.

Signed-off-by: Sonali Saha <sonali.saha@intel.com>
```

**Comment by dimakuv** [comment]
This was fixed as part of https://github.com/gramineproject/contrib/pull/28, closing here.

**Pull request closed without merging**
