### PR TITLE
[Curated-Apps] Use v1.4 version of Gramine and GSC

### PR DESCRIPTION
**Pull request by jkr0103**
As we have Gramine and GSC tagged with v1.4, Curated-Apps can use the latest released version of Gramine and GSC.
PR changes the Gramine and GSC version to v1.4 in Curated-Apps.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/.gitignore` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOsbrns9QxFkRyIw8_1:-NOsbrns9QxFkRyIw8_2:badnpor) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/.gitignore#L2)):*
> ```ignore
> /commands.txt
> /gsc
> ```

Could you please add the "newline" symbol in this line?
___
*[`Curated-Apps/util/config.yaml.template` line 41 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOsc7OA0KS7l7KRHuMO:-NOsc7OB7b6AhRQoDDLi:b-5tw7lr) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/util/config.yaml.template#L41)):*
> ```
> SGXDriver:
>     Repository: ""
>     Branch:     ""
> ```

Actually, why not just remove all the comments from here? They are useless anyway, noone is supposed to look into this file when using Curated Apps.
___
*[`Curated-Apps/util/curation_script.sh` line 120 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscFcC1OdRT_CS8ajD:-NOscFcC1OdRT_CS8ajE:b-cjx7ao) ([raw file](https://github.com/gramineproject/contrib/blob/d8142285dada9a5406c217cf1c2c36445f695196/Curated-Apps/util/curation_script.sh#L120)):*
> ```Shell
> 
>     cd ../
>     rm -rf gsc >/dev/null 2>&1
> ```

Why did you remove this, and what was the initial purpose of this deletion?
___
*[`Curated-Apps/workloads/pytorch/pytorch.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscOQm69513-hu_Vi9:-NOscOQm69513-hu_ViA:bclmn4) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/workloads/pytorch/pytorch.manifest.template#L10)):*
> ```
> sgx.enclave_size = "4G"
> sgx.max_threads = 128
> loader.pal_internal_mem_size = "128M"
> ```

You can remove this (from everywhere in Curated Apps) -- this manifest option is completely ignored in Gramine in v1.4
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscXyFAwtigv_D0rpr:-NOscXyFAwtigv_D0rps:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L10)):*
> ```
> sgx.enclave_size = "16G"
> sgx.max_threads = 128
> loader.pal_internal_mem_size = "128M"
> ```

ditto
___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscagi-8I_upPrjnPn:-NOscagjApOHEPuZMuwC:b-7ropln) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template#L10)):*
> ```
> sgx.enclave_size = "64G"
> sgx.max_threads = 1024
> loader.pal_internal_mem_size = "128M"
> ```

ditto

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: 4 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/.gitignore` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOsbrns9QxFkRyIw8_1:-NOsu98VEjiA3B8TCZOx:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/.gitignore#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you please add the "newline" symbol in this line?
</blockquote></details>

Done.
___
*[`Curated-Apps/util/config.yaml.template` line 41 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOsc7OA0KS7l7KRHuMO:-NOsuAEM8-wMJbHO1or-:b-gfy04b) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/util/config.yaml.template#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why not just remove all the comments from here? They are useless anyway, noone is supposed to look into this file when using Curated Apps.
</blockquote></details>

We actually don't need that file in Curated-Apps, can use file from GSC directly. I think thought behind putting it in Curated-Apps was to give flexibility to user to choose OOT SGX driver, but now as we have dropped the OOT SGX driver support with new release of gramine, there is no need to keep it here. Hence removed it.
___
*[`Curated-Apps/util/curation_script.sh` line 120 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscFcC1OdRT_CS8ajD:-NOsupOI0qr1a86viTVY:b-ooxwfx) ([raw file](https://github.com/gramineproject/contrib/blob/d8142285dada9a5406c217cf1c2c36445f695196/Curated-Apps/util/curation_script.sh#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this, and what was the initial purpose of this deletion?
</blockquote></details>

Not sure about why GSC repo was deleted after curation was complete but keeping GSC repo after curation have helped in debuging, specially `GSC/build`. Anyways GSC repo is deleted and created again on next run of curation here https://github.com/gramineproject/contrib/blob/d8142285dada9a5406c217cf1c2c36445f695196/Curated-Apps/util/curation_script.sh#L89 which eliminates posibilities of using stale GSC repo. So I don't see any harm to keep it until next run of curation.
___
*[`Curated-Apps/workloads/pytorch/pytorch.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscOQm69513-hu_Vi9:-NOswexgEyx52QBy4mcs:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/workloads/pytorch/pytorch.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can remove this (from everywhere in Curated Apps) -- this manifest option is completely ignored in Gramine in v1.4
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/sklearn/sklearn.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscXyFAwtigv_D0rpr:-NOswfZu2fk-OKMHdgkX:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/workloads/sklearn/sklearn.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscagi-8I_upPrjnPn:-NOswg9Q8bbEStcqNNU5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/9719a8cd2b86eac82323981931ccffe432ad2397/Curated-Apps/workloads/tensorflow-serving/tensorflow-serving.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Curated-Apps/util/curation_script.sh` line 120 at r1](https://reviewable.io/reviews/gramineproject/contrib/36#-NOscFcC1OdRT_CS8ajD:-NOtAfdh2an55ey55jkh:bexfl8h) ([raw file](https://github.com/gramineproject/contrib/blob/d8142285dada9a5406c217cf1c2c36445f695196/Curated-Apps/util/curation_script.sh#L120)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Not sure about why GSC repo was deleted after curation was complete but keeping GSC repo after curation have helped in debuging, specially `GSC/build`. Anyways GSC repo is deleted and created again on next run of curation here https://github.com/gramineproject/contrib/blob/d8142285dada9a5406c217cf1c2c36445f695196/Curated-Apps/util/curation_script.sh#L89 which eliminates posibilities of using stale GSC repo. So I don't see any harm to keep it until next run of curation.
</blockquote></details>

Ok, fine with me

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r1, 5 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/util/curation_script.sh` line 172 at r4](https://reviewable.io/reviews/gramineproject/contrib/36#-NPJX51p8aLXXt4Jss44:-NPJX51p8aLXXt4Jss45:b-2szqwn) ([raw file](https://github.com/gramineproject/contrib/blob/1152102755730c6ac74735ba3609d1fa42322d93/Curated-Apps/util/curation_script.sh#L172)):*
> ```Shell
> echo '#!/usr/bin/env bash' >> $entrypoint_script
> echo '' >> $entrypoint_script
> echo $complete_binary_cmd' "${@}"' >> $entrypoint_script
> ```

How does these single quotes here work? Have you tested this?



_Code quote:_
```Shell
echo $complete_binary_cmd' "${@}"'
```

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Curated-Apps/util/curation_script.sh` line 172 at r4](https://reviewable.io/reviews/gramineproject/contrib/36#-NPJX51p8aLXXt4Jss44:-NPLL7YPB-GeoCM67HH9:b-e9eb7k) ([raw file](https://github.com/gramineproject/contrib/blob/1152102755730c6ac74735ba3609d1fa42322d93/Curated-Apps/util/curation_script.sh#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How does these single quotes here work? Have you tested this?
</blockquote></details>

Single quotes are required to keep the double quotes around `${@}` when it's added to `entry_script_xxx.sh` file because that's necessary in shell. For example, this line looks like `"python3" "pytorchexample.py"  "${@}"` when added to PyTorch's`entry_script_pytorch.sh`.

**Review by mkow — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/util/curation_script.sh` line 172 at r4](https://reviewable.io/reviews/gramineproject/contrib/36#-NPJX51p8aLXXt4Jss44:-NPNYZ_QBHJAsaBHI-H-:b-ji90hl) ([raw file](https://github.com/gramineproject/contrib/blob/1152102755730c6ac74735ba3609d1fa42322d93/Curated-Apps/util/curation_script.sh#L172)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Single quotes are required to keep the double quotes around `${@}` when it's added to `entry_script_xxx.sh` file because that's necessary in shell. For example, this line looks like `"python3" "pytorchexample.py"  "${@}"` when added to PyTorch's`entry_script_pytorch.sh`.
</blockquote></details>

But you also removed them from `'$complete_binary_cmd'` in this PR. If the previous version of the code worked, then I don't see how the current could work?

**Review by mkow — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/util/curation_script.sh` line 172 at r4](https://reviewable.io/reviews/gramineproject/contrib/36#-NPJX51p8aLXXt4Jss44:-NPNZ1kxAmp_R9BsG2KJ:b-l63zi9) ([raw file](https://github.com/gramineproject/contrib/blob/1152102755730c6ac74735ba3609d1fa42322d93/Curated-Apps/util/curation_script.sh#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But you also removed them from `'$complete_binary_cmd'` in this PR. If the previous version of the code worked, then I don't see how the current could work?
</blockquote></details>

Also, this change is committed in a commit titled "Use v1.4 version of Gramine and GSC"...

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Curated-Apps/util/curation_script.sh` line 172 at r4](https://reviewable.io/reviews/gramineproject/contrib/36#-NPJX51p8aLXXt4Jss44:-NPNoSeb82kbIgVQI8eU:b-x0thfd) ([raw file](https://github.com/gramineproject/contrib/blob/1152102755730c6ac74735ba3609d1fa42322d93/Curated-Apps/util/curation_script.sh#L172)):*
> But you also removed them from '$complete_binary_cmd' in this PR. If the previous version of the code worked, then I don't see how the current could work?

`$complete_binary_cmd` was not wrapped around single quotes in old code, if you observe closely you will find it though it gives illusion that it's wrapped around single quotes.

>Also, this change is committed in a commit titled "Use v1.4 version of Gramine and GSC"...

I did not understand it.

**Review by mkow — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`Curated-Apps/util/curation_script.sh` line 172 at r4](https://reviewable.io/reviews/gramineproject/contrib/36#-NPJX51p8aLXXt4Jss44:-NPORqL74UZFtvyZvrCR:bc1pave) ([raw file](https://github.com/gramineproject/contrib/blob/1152102755730c6ac74735ba3609d1fa42322d93/Curated-Apps/util/curation_script.sh#L172)):*
> if you observe closely you will find it though it gives illusion that it's wrapped around single quotes.

:scream:
This is like reading obfuscated code...

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/36)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
