### PR TITLE
Release 1.6.1

### LINKED ISSUE #78: Verifier build fails with error `Version '1.6' for 'gramine' was not found`
**Steps to Reproduce:**
Build any workload by choosing attestation as test or done(provide ssl keys)

**Error:**
```
RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y     libsgx-dcap-default-qpl=1.16.100.2-jammy1     gramine=1.6
 ---> Running in dde3d482917e
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy InRelease [1236 B]
Get:6 https://download.01.org/intel-sgx/sgx_repo/ubuntu jammy/main amd64 Packages [64.0 kB]
Get:7 https://packages.gramineproject.io jammy InRelease [3275 B]
Get:8 https://packages.gramineproject.io jammy/main amd64 Packages [1059 B]
Fetched 69.6 kB in 3s (25.7 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package gramine is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

[91mE: Version '1.6' for 'gramine' was not found
[0mThe command '/bin/sh -c env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y     libsgx-dcap-default-qpl=1.16.100.2-jammy1     gramine=1.6' returned a non-zero code: 100
```

[pytorch_with_attestation_encrypted_image_verifier.log](https://github.com/gramineproject/contrib/files/14354138/test_pytorch_with_attestation_encrypted_image_verifier.log)

### PR DESCRIPTION
**Pull request by woju**
Fixes #78

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/80)

### CODE REVIEW

**Review by dimakuv — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/80)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by mkow — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/80)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/80)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/80)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/80)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
