### PR TITLE
[Curated-Apps] Update Gramine docs link

### PR DESCRIPTION
**Pull request by jkr0103**
Some workloads uses latest version of gramine documentation which is broken now instead curated app should use the stable version.

This PR uses the stable version of gramine documentation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/48)

### CODE REVIEW

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/48)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/48#-NXfNVMgDPFs9jlebgo9):*




_Suggestion:_
```
Update Gramine docs link
```

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/48)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/48#-NXiHBun39HQJGXZDvrJ:-NXiHBun39HQJGXZDvrK:boddj2t) (no related file):*
I think it will get broken soon-ish, when we'll have a release v1.6 (because that stable version would have a new structure of the documents). But we can fix it later I guess, let's fix what we currently have.

___

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/48)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/48#-NXfNVMgDPFs9jlebgo9):*
Done

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/48)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/48)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
