### PR TITLE
Release 1.7

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/86)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/86)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/86)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/86#-Nw9niJV1tgcYIzHgogi:-Nw9niJV1tgcYIzHgogj:b-j9j5ja) (no related file):*
TODO: check commit split before merging

___
*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/86#-Nw9oEkh8QZ3Wehjvjv4:-Nw9oEkh8QZ3Wehjvjv5:b-5miv6r) (no related file):*
Blocking until RC is removed.

___

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/86)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/86)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
