### PR TITLE
[Curated-Apps] Add memcached

### PR DESCRIPTION
**Pull request by sahason**
Updating the Curated script and packages to add Memcached.

Currently, the PR is depending on PR #39.

Merging orders should be
PR #39
PR #35

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZRvt9As3SO91s-rFk:-NQZRvt9As3SO91s-rFl:bhrx68e) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L13)):*
> ```
> # COPY ca.crt /ca.crt
> 
> # These two lines are required to incorporate command-line arguments with the image entrypoint and cmd
> ```

This exceeds 100 chars per line. You can just replace `arguments` -> `args`, and then the line will fit.
___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NQZS6MH43tF2JIl1Aj8:brw5k) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
> ```
> # These two lines are required to incorporate command-line arguments with the image entrypoint and cmd
> COPY entry_script_memcached.sh /usr/local/bin/entry_script_memcached.sh
> ENTRYPOINT ["/bin/bash", "/usr/local/bin/entry_script_memcached.sh"]
> ```

Could you remind me, this `entry_script_memcached.sh` is generated automatically by the Curated Apps script?

If yes, maybe you could add an additional comment before these two lines? Like this:
```
# The curation script generates the entry_script_memcached.sh file
```
___
*[`Curated-Apps/workloads/memcached/README.md` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZSPpp6_5Sk2yhWFlY:-NQZSPpq6czzdT6rz5XL:bfen651) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L2)):*
> ```Markdown
> # Gramine Curated Memcached
> In the following two sections, we explain how a Docker image for the protected memcached version can be
> ```

This whole file needs to be reformatted so that each line fits into 100 chars. Please do it.

Also, shouldn't `memcached` be written with a capital letter everywhere? Please fix.
___
*[`Curated-Apps/workloads/memcached/README.md` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZSgrj9YnMXx5X33iH:-NQZSgrk1GPtgYHvrPSG:biasjmc) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L8)):*
> ```Markdown
> 
> ## Build a confidential compute image for Memcached
> Execute the below commands on the VM.
> ```

Why do you talk about `VM`? This is not necessary. Can't you just replace with `on your system`?
___
*[`Curated-Apps/workloads/memcached/README.md` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZTNfy5BLM6ufxzw84:-NQZTNfy5BLM6ufxzw85:bqk1g9p) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L18)):*
> ```Markdown
>        $ cd contrib/Curated-Apps
> 
> 3. To generate a preconfigured confidential compute image for Memcached, execute the following script:
> ```

Shouldn't you also add a `test ... image`, because this is not suitable for production, right? You have the `test` argument there, and you should make it clear somehow.
___
*[`Curated-Apps/workloads/memcached/README.md` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZT3Ty-kC_LgtqsJ9Q:-NQZT3Ty-kC_LgtqsJ9R:bj02p5p) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L20)):*
> ```Markdown
> 3. To generate a preconfigured confidential compute image for Memcached, execute the following script:
> 
>        $ python3 ./curate.py memcached ubuntu/memcached:1.5-20.04_beta test
> ```

Why do Memcached images have `beta` in the name? I looked at them (https://hub.docker.com/r/ubuntu/memcached/tags), and indeed all images are either `beta` or `edge`, which looks weird to me.

I'm not blocking on this comment, I'm just curious what's the deal with this suffix.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: 1 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 13 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZRvt9As3SO91s-rFk:-NQaStjW7PRqbY9R3pBV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This exceeds 100 chars per line. You can just replace `arguments` -> `args`, and then the line will fit.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NQaSvI9-IoD-R61W8bL:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you remind me, this `entry_script_memcached.sh` is generated automatically by the Curated Apps script?

If yes, maybe you could add an additional comment before these two lines? Like this:
```
# The curation script generates the entry_script_memcached.sh file
```
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/memcached/README.md` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZSPpp6_5Sk2yhWFlY:-NQaSw__ASQnE6M0zSOd:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole file needs to be reformatted so that each line fits into 100 chars. Please do it.

Also, shouldn't `memcached` be written with a capital letter everywhere? Please fix.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/memcached/README.md` line 8 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZSgrj9YnMXx5X33iH:-NQaSx3zDEZfzEo88-eV:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you talk about `VM`? This is not necessary. Can't you just replace with `on your system`?
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/memcached/README.md` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZTNfy5BLM6ufxzw84:-NQaSxwB3cZwhoBJLWhW:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you also add a `test ... image`, because this is not suitable for production, right? You have the `test` argument there, and you should make it clear somehow.
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/memcached/README.md` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZT3Ty-kC_LgtqsJ9Q:-NQaT49L8vHq4hVJ0YNh:b4quqjn) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do Memcached images have `beta` in the name? I looked at them (https://hub.docker.com/r/ubuntu/memcached/tags), and indeed all images are either `beta` or `edge`, which looks weird to me.

I'm not blocking on this comment, I'm just curious what's the deal with this suffix.
</blockquote></details>

Based on this link https://hub.docker.com/r/ubuntu/memcached I have used this image. But now I also noticed that all the images are either beta or edge.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NQdiYV58hctihav-K4Q:btvuu4e) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This entry script will be removed by https://github.com/gramineproject/contrib/pull/39.

I think PR 39 will go first, so you'll need to update your PR to NOT use this.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: 1 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NQe0FYkDUJeW91-YJ-h:b4svs8b) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This entry script will be removed by https://github.com/gramineproject/contrib/pull/39.

I think PR 39 will go first, so you'll need to update your PR to NOT use this.
</blockquote></details>

I have done this today. There was one issue with PR #39 which is fixed now.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NQelMid0jKmAq709v2B:b-yjbz4) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have done this today. There was one issue with PR #39 which is fixed now. 
</blockquote></details>

Thanks, I'll keep it blocking for now.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NQzk7rz1AyY9SaKcJJx:b-wn3ar9) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, I'll keep it blocking for now.
</blockquote></details>

PR was merge now, please update your PR and verify that it works correctly.

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 15 at r1](https://reviewable.io/reviews/gramineproject/contrib/35#-NQZS6MH43tF2JIl1Aj7:-NR1n3OgCC45E6UO--ni:b-9lfivc) ([raw file](https://github.com/gramineproject/contrib/blob/34de96985a082907c16c1ffc067ad141a05f5761/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

PR was merge now, please update your PR and verify that it works correctly.
</blockquote></details>

I have updated the PR and verified that it works correctly.

**Review by dimakuv — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 11 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGGvUmBsfclA7zg9hO:-NRGGvUmBsfclA7zg9hP:b-5fjwm0) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L11)):*
> ```
> FROM <base_image_name>
> 
> # COPY ca.crt /ca.crt
> ```

Why is this a comment?
___
*[`Curated-Apps/workloads/memcached/memcached.manifest.template` line 12 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGHB5v4NYg4DxjLH61:-NRGHB5v4NYg4DxjLH62:b-ak3vb6) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached.manifest.template#L12)):*
> ```
> # This is required to run workload as non-root user, any number works except `0` which is for root.
> loader.uid=999
> loader.gid=999
> ```

spaces around `=`
___
*[`Curated-Apps/workloads/memcached/README.md` line 1 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGH_18AIYy2vRe-Hjf:-NRGH_18AIYy2vRe-Hjg:bu83s0p) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/README.md#L1)):*
> ```Markdown
> # Gramine Curated Memcached
> ```

please add empty lines after headings

**Review by sahason — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 11 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGGvUmBsfclA7zg9hO:-NRGNyjyAi1TmrfidA6j:bec52ue) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this a comment?
</blockquote></details>

Adding @jkr0103 to explain it better.
___
*[`Curated-Apps/workloads/memcached/memcached.manifest.template` line 12 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGHB5v4NYg4DxjLH61:-NRGO6J61k9DEUNLBO_F:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached.manifest.template#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

spaces around `=`
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/memcached/README.md` line 1 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGH_18AIYy2vRe-Hjf:-NRGO7Ae44Of41cCPIOv:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/README.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please add empty lines after headings
</blockquote></details>

Done.

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 11 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGGvUmBsfclA7zg9hO:-NRGq-e31RQt62V4uZBJ:b-ixejr3) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L11)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Adding @jkr0103 to explain it better.
</blockquote></details>

`ca.crt` in GSC image is required only for Remote attestation case and it is uncommented by `curation_script.sh` if user selects remote attestation via UI.

I think we can add a comment something like:

`# Below line is uncommented if user selects remote attestation via UI`

@mkow What's you opinion on that?

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 11 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGGvUmBsfclA7zg9hO:-NRHiYWpCjW3EKYdf-LL:b-i33l0g) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L11)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

`ca.crt` in GSC image is required only for Remote attestation case and it is uncommented by `curation_script.sh` if user selects remote attestation via UI.

I think we can add a comment something like:

`# Below line is uncommented if user selects remote attestation via UI`

@mkow What's you opinion on that?
</blockquote></details>

Yes, we can add such a comment. I remember how it works from our previous discussions on this topic :)

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/35#-NRdA8CNEw1J7Qp-A4_Z:-NRdA8CQ7NOvzDXR4N0Y:b-cd8omz) (no related file):*
@sahason Could you rebase your PR on the latest master and incorporate the latest changes?

___
___
*[`Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template` line 11 at r4](https://reviewable.io/reviews/gramineproject/contrib/35#-NRGGvUmBsfclA7zg9hO:-NRdAIlCAyicl1In1yqJ:bgmmxj8) ([raw file](https://github.com/gramineproject/contrib/blob/e6d8272137238ec004102674b179210d8d58233a/Curated-Apps/workloads/memcached/memcached-gsc.dockerfile.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, we can add such a comment. I remember how it works from our previous discussions on this topic :)
</blockquote></details>

We have a different way now, please fix it

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @sahason)

___
*[`Curated-Apps/workloads/memcached/README.md` line 25 at r7](https://reviewable.io/reviews/gramineproject/contrib/35#-NRgZ1MD6SfzONhmtNEn:-NRgZ1MD6SfzONhmtNEo:b-wltcbi) ([raw file](https://github.com/gramineproject/contrib/blob/8b733a588d574f6072f01e0cc60d88bbc4a97433/Curated-Apps/workloads/memcached/README.md#L25)):*
>To generate

Or, to generate

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @sahason)

**Review by jkr0103 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35#-:-NRkZxix265d_zk1452f:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
