### PR TITLE
Release 1.6

### PR DESCRIPTION
**Pull request by woju**
Synces version numbers with Gramine release.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/changelog` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/67#-NleAIl24u6tIyQMMtlc:-NleAIl24u6tIyQMMtld:bwq60iw) ([raw file](https://github.com/gramineproject/contrib/blob/c17ef61cfa64e41920435a2c1b4481b67326dccf/debian/changelog#L4)):*
> ```
> 
>   * Initial packaging
>   * Only gramine-ratls-maa is curretnly built
> ```

`currently` (typo)
___
*[`debian/changelog` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/67#-NleAOOt0ZPGTvYXdwvW:-NleAOOt0ZPGTvYXdwvX:bdoww50) ([raw file](https://github.com/gramineproject/contrib/blob/c17ef61cfa64e41920435a2c1b4481b67326dccf/debian/changelog#L6)):*
> ```
>   * Only gramine-ratls-maa is curretnly built
> 
>  -- Wojtek Porczyk <woju@invisiblethingslab.com>  Thy, 14 Dec 2023 22:00:00 +0100
> ```

`Thu` (typo? Is this some Polish?)
___
*[`debian/changelog` line 3 at r2](https://reviewable.io/reviews/gramineproject/contrib/67#-NleAcNn6E99_oeewtBz:-NleAcNn6E99_oeewtC-:bnul8wg) ([raw file](https://github.com/gramineproject/contrib/blob/c85c06d26e7238e482d53b8350e401e65ba092b6/debian/changelog#L3)):*
> ```
> gramine-contrib (1.6post~UNRELEASED) UNRELEASED; urgency=medium
> 
>   * 
> ```

A redundant space?
___
*[`debian/changelog` line 5 at r2](https://reviewable.io/reviews/gramineproject/contrib/67#-NleA_qGCBPWDSuSXoX7:-NleA_qGCBPWDSuSXoX8:b-7u9jl2) ([raw file](https://github.com/gramineproject/contrib/blob/c85c06d26e7238e482d53b8350e401e65ba092b6/debian/changelog#L5)):*
> ```
>   * 
> 
>  -- Wojtek Porczyk <woju@invisiblethingslab.com>  Thy, 14 Dec 2023 22:00:01 +0100
> ```

`Thu`

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/67#-NlgRDf27kZYSeFskYo0:-NlgRDf27kZYSeFskYo1:b-ts8j38) (no related file):*
Blocking this PR until GSC is tagged with v1.6 release and @jkr0103 moves curated apps to 1.6 GSC.

___

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/67#-NlgRDf27kZYSeFskYo0:-NmCNUnV4FRNbqsSx3n2:bxvb6yt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking this PR until GSC is tagged with v1.6 release and @jkr0103 moves curated apps to 1.6 GSC.
</blockquote></details>

We can unblock this PR now as GSC is tagged with v1.6 and contrib is using Gramine v1.6 now.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: 1 of 3 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`debian/changelog` line 4 at r1](https://reviewable.io/reviews/gramineproject/contrib/67#-NleAIl24u6tIyQMMtlc:-NoCh84j573azF5WZDpq:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c17ef61cfa64e41920435a2c1b4481b67326dccf/debian/changelog#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`currently` (typo)
</blockquote></details>

Done.
___
*[`debian/changelog` line 6 at r1](https://reviewable.io/reviews/gramineproject/contrib/67#-NleAOOt0ZPGTvYXdwvW:-NoCh7pP9I-eX-fs3BVq:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c17ef61cfa64e41920435a2c1b4481b67326dccf/debian/changelog#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Thu` (typo? Is this some Polish?)
</blockquote></details>

Done.
___
*[`debian/changelog` line 3 at r2](https://reviewable.io/reviews/gramineproject/contrib/67#-NleAcNn6E99_oeewtBz:-NoChA618_xvo_HKbSPH:bclhjof) ([raw file](https://github.com/gramineproject/contrib/blob/c85c06d26e7238e482d53b8350e401e65ba092b6/debian/changelog#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A redundant space?
</blockquote></details>

No, it's OK, it's waiting for the entry.
___
*[`debian/changelog` line 5 at r2](https://reviewable.io/reviews/gramineproject/contrib/67#-NleA_qGCBPWDSuSXoX7:-NoCh8T25dJBBup3Gbdh:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/c85c06d26e7238e482d53b8350e401e65ba092b6/debian/changelog#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Thu`
</blockquote></details>

Done.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/67#-NoCj_ZfCC0RHxXn6oww:-NoCj_ZfCC0RHxXn6owx:b2rkwig) (no related file):*
So should https://github.com/gramineproject/contrib/pull/72 go before this PR?

___

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/67#-NoCj_ZfCC0RHxXn6oww:-NoMjN1w2371wxuvWtLM:b-plzh5l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So should https://github.com/gramineproject/contrib/pull/72 go before this PR?
</blockquote></details>

We agreed privately with @woju that #72 goes first. It was merged already, and this PR was rebased to the latest master now. I'm unblocking.

___

**Review by kailun-qin — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by kailun-qin — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
