### PR TITLE
Workaround for the packaging issue with v1.3

### PR DESCRIPTION
**Pull request by jkr0103**
Workaround for the packaging issue with v1.3

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)

### CODE REVIEW

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

**Review by woju — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @mkow)

___
*[`Curated-Apps/curate.py` line 472 at r1](https://reviewable.io/reviews/gramineproject/contrib/9#-NCzG-vFAiuvZT8yr8s1:-NCzIiSY2RV2urLjkON8:b-dbcq3v) ([raw file](https://github.com/gramineproject/contrib/blob/df54cd0cdb072e4072f61564339f7a1b3947e5ad/Curated-Apps/curate.py#L472)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this seems unrelated?
</blockquote></details>

Done. Commit message is added to reflect this.

**Review by dimakuv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/9#-NCzFw25DfEkEsBR5DSI):*
Done

**Review by woju — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
