### PR TITLE
Update AKS attestation example to work V1.2 Gramine release

### PR DESCRIPTION
**Pull request by aneessahib**
Example updated to work with Gramine V1.2 release, among other changes to ensure this example does not break in between releases while Gramine master progresses.

---
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TamPN8T3NQBzTcrOx):*
`work V1.2` -> `with with v1.2`

Can be done during final rebase.
___
*[`Examples/aks-attestation/aks-secret-prov-server.dockerfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Tewd1-4INwkp8I4C8:-N3Tewd23I9XR2hLtlfv:b-g0bv7m) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/aks-secret-prov-server.dockerfile#L7)):*
> ```Dockerfile
>     gnupg2 \
>     wget \
>     curl
> ```

Please sort these three.
___
*[`Examples/aks-attestation/aks-secret-prov-server.dockerfile` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Tc6_D6YRBeqwQbnxb:-N3Tc6_D6YRBeqwQbnxc:b-ta3tcz) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/aks-secret-prov-server.dockerfile#L28)):*
> ```Dockerfile
>     && apt-key add intel-sgx-deb.key
> 
> # Install Gramine dcap package.
> ```

This comment is useless, I would just remove it.
___
*[`Examples/aks-attestation/base-image-generation-script.sh` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Teky94Cmz4L9wondK:-N3Teky94Cmz4L9wondL:b2qs7kq) ([raw file](https://github.com/gramineproject/contrib/blob/a5cf0766fb836e19e650de966406ae3e06436994/Examples/aks-attestation/base-image-generation-script.sh#L3)):*
> ```Shell
> # Download and build Gramine. We need it to build and copy ra-tls-secret-prov files and
> # relevant libraries into the server and client Dockerfiles.
> if [ -d "gramine" ]; then
> ```

Why did you remove this check on the existence of the `gramine/` directory? This sounds reasonable to have.
___
*[`Examples/aks-attestation/install_gramine.sh` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Te1YO3DOzJI21ZUR6:-N3Te1YO3DOzJI21ZUR7:b50cm04) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L3)):*
> ```Shell
> # This script assumes that dcap driver is installed on the host system.
> # Please refer to https://gramine.readthedocs.io/en/latest/devel/building.html#install-the-intel-sgx-driver
> # for more details.
> ```

But you don't really need anything SGX-related at all on the host system. We don't build any `.manifest.sgx` files in this script, and we don't build Gramine, we only install the package. So nothing SGX-related needs to be specified here.

Please remove this comment.
___
*[`Examples/aks-attestation/install_gramine.sh` line 11 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TeKeS-HznT6hlvkWQ:-N3TeKeS-HznT6hlvkWR:b-mcq43u) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L11)):*
> ```Shell
> 
> sudo apt-get update
> sudo apt-get install gramine-dcap # for out-of-tree DCAP driver
> ```

Can you please add `...for out-of-tree DCAP driver (required by AKS Ubuntu 18.04 distro)`
___
*[`Examples/aks-attestation/install_gramine.sh` line 13 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TeU199fVx5syoy7Tp:-N3TeU199fVx5syoy7Tq:buuxoh1) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L13)):*
> ```Shell
> sudo apt-get install gramine-dcap # for out-of-tree DCAP driver
> 
> # Generate signing key
> ```

The comment is useless, just remove
___
*[`Examples/aks-attestation/install_gramine.sh` line 14 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TeRhFBF0-yYaXGrVp:-N3TeRhFBF0-yYaXGrVq:b-l9r8dl) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L14)):*
> ```Shell
> 
> # Generate signing key
> bash -c "gramine-sgx-gen-private-key"
> ```

Why do you need to wrap this into `bash`? Just call this tool directly.
___
*[`Examples/aks-attestation/install_gramine.sh` line 16 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Te__-5m1kIpBjkjkm:-N3Te__-5m1kIpBjkjkn:buuxoh1) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L16)):*
> ```Shell
> bash -c "gramine-sgx-gen-private-key"
> 
> # Clone Gramine(v1.2) source.
> ```

The comment is useless, just remove
___
*[`Examples/aks-attestation/install_gramine.sh` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Tea3N9LIrbMFc1JTm:-N3Tea3N9LIrbMFc1JTn:b-zdokl2) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L18)):*
> ```Shell
> # Clone Gramine(v1.2) source.
> git clone https://github.com/gramineproject/gramine.git --depth=1
> cd gramine && git fetch --all --tags && git checkout v1.2
> ```

Instead of this `git fetch`, you can simply do: `git clone --depth 1 https://github.com/gramineproject/gramine.git v1.2`
___
*[`Examples/aks-attestation/install_gramine.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TfRZM0QGyaNk73lOB:-N3TfRZM0QGyaNk73lOC:b-lh0yx1) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L22)):*
> ```Shell
> # Copy dummy server certificate with Common Name as "<AKS-DNS-NAME.*.cloudapp.azure.com>
> cd ../
> cp -r certs/* gramine/CI-Examples/ra-tls-secret-prov/ssl
> ```

Please rename the `certs/` directory in this AKS example to `ssl/`. Then we'll have uniform names between this AKS example and the `ra-tls-secret-prov` core example. And also readers of this code won't be surprised "why is there a difference in names".
___
*[`Examples/aks-attestation/README.md` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TcTLC1gYLxpcbgEfV:-N3TcTLC1gYLxpcbgEfW:bfm1tr1) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/README.md#L36)):*
> ```Markdown
> AKS cluster.
> 
> Note: This example is Ubuntu-specific (tested version is Ubuntu 18.04).
> ```

Actually, this is *very much* Ubuntu 18.04 specific. Because we install `gramine-dcap` version, which is only relevant for Ubuntu 18.04 (which has an out-of-tree DCAP driver). For Ubuntu 20.04, rather significant changes will be needed here.

Also, we explicitly use (hard-code) v1.2 of Gramine, which also should be mentioned.

So I suggest to be more specific:
```
Note: This example is Ubuntu 18.04-specific. This example was tested with Gramine v1.2.
```
___
*[`Examples/aks-attestation/certs/README` line 12 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TbZ5J8zNN7R1_IkNu:-N3TbZ5J8zNN7R1_IkNv:b7fdjpn) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/certs/README#L12)):*
> ```
> 
> Note: These certificates should not be used in production. Here, user should
>       update the server2-sha256.crt with ``Common Name`` pointing to the DNS
> ```

`server.crt`

**Review by aneessahib — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: 4 of 11 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[`Examples/aks-attestation/aks-secret-prov-server.dockerfile` line 7 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Tewd1-4INwkp8I4C8:-N3TxzvJ3pmJV1Mq4zbP:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/aks-secret-prov-server.dockerfile#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort these three.
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/aks-secret-prov-server.dockerfile` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Tc6_D6YRBeqwQbnxb:-N3Ty-tL5h37i96C7jR3:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/aks-secret-prov-server.dockerfile#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is useless, I would just remove it.
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/base-image-generation-script.sh` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Teky94Cmz4L9wondK:-N3Ty0mxCHYSXLafdHx8:b57xka3) ([raw file](https://github.com/gramineproject/contrib/blob/a5cf0766fb836e19e650de966406ae3e06436994/Examples/aks-attestation/base-image-generation-script.sh#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this check on the existence of the `gramine/` directory? This sounds reasonable to have.
</blockquote></details>

Technically, there should not be a `gramine` directory here in the first place. The scripts takes care of creating and deleting this. If there's indeed a stale one present, then we should actually delete it and proceed, as opposed to re-using it like before (since this could be based on some random commit).
___
*[`Examples/aks-attestation/install_gramine.sh` line 3 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Te1YO3DOzJI21ZUR6:-N3U2qzf2PWqQnso1Mg5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you don't really need anything SGX-related at all on the host system. We don't build any `.manifest.sgx` files in this script, and we don't build Gramine, we only install the package. So nothing SGX-related needs to be specified here.

Please remove this comment.
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/install_gramine.sh` line 11 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TeKeS-HznT6hlvkWQ:-N3U2s0G2zwEYLWg3qoY:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you please add `...for out-of-tree DCAP driver (required by AKS Ubuntu 18.04 distro)`
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/install_gramine.sh` line 13 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TeU199fVx5syoy7Tp:-N3U2sstE5TC5WdcoEQq:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is useless, just remove
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/install_gramine.sh` line 14 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TeRhFBF0-yYaXGrVp:-N3U2tnFD70iZtQO-ghf:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need to wrap this into `bash`? Just call this tool directly.
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/install_gramine.sh` line 16 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Te__-5m1kIpBjkjkm:-N3U2uLB3lp_--v8CA_-:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is useless, just remove
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/install_gramine.sh` line 18 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3Tea3N9LIrbMFc1JTm:-N3U2v0-8sL-s64Z7PKR:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of this `git fetch`, you can simply do: `git clone --depth 1 https://github.com/gramineproject/gramine.git v1.2`
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/install_gramine.sh` line 22 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TfRZM0QGyaNk73lOB:-N3U2vfK0RlgUArLsUX4:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/install_gramine.sh#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename the `certs/` directory in this AKS example to `ssl/`. Then we'll have uniform names between this AKS example and the `ra-tls-secret-prov` core example. And also readers of this code won't be surprised "why is there a difference in names".
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/README.md` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TcTLC1gYLxpcbgEfV:-N3U2wv2APGd4YvIG0XF:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/README.md#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, this is *very much* Ubuntu 18.04 specific. Because we install `gramine-dcap` version, which is only relevant for Ubuntu 18.04 (which has an out-of-tree DCAP driver). For Ubuntu 20.04, rather significant changes will be needed here.

Also, we explicitly use (hard-code) v1.2 of Gramine, which also should be mentioned.

So I suggest to be more specific:
```
Note: This example is Ubuntu 18.04-specific. This example was tested with Gramine v1.2.
```
</blockquote></details>

Done.
___
*[`Examples/aks-attestation/certs/README` line 12 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TbZ5J8zNN7R1_IkNu:-N3U2yDQ0350629XXiur:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/e61e6af93b51a4a901458df37240ebf727501c99/Examples/aks-attestation/certs/README#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`server.crt`
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/5#-N3U_VGf76AR6r2On8cV:-N3U_VGg2LAgpRA-gl3x:b-zevst6) (no related file):*
@aneessahib @veenasai2 Could you double-check that this latest version works correctly on AKS? Just to be sure. I'm approving, but want to be sure.

___

**Review by mkow — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by dimakuv — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @woju)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/contrib/5#-N3TamPN8T3NQBzTcrOx):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`work V1.2` -> `with with v1.2`

Can be done during final rebase.
</blockquote></details>

Done.

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
