### PR TITLE
[Curated-Apps] Improvements in READMEs

### PR DESCRIPTION
**Pull request by jkr0103**
List of changes in PR:
1. Removed the `$`symbols from beginning of sh commands which helps in directly executing the commands after copying using copy button that appears at the right of `sh` block.
2. Added `tomli and tomli-w` packages to prerequisites which will be required when Curated-Apps start using GSC v1.4
3. Some prerequisite packages `torchvision, pillow, scikit-learn-intelex` for `Scikit-learn` and `PyTorch` apps are not available with default pip version on `ubuntu 18.04`. For this we need to upgrade pip version.
4. Added missing prerequisites step in `Pytorch` and `Scikit-learn` apps READMEs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Curated-Apps/README.md` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5HrzJ8-vSOWbKZLsH:-NL5HrzJ8-vSOWbKZLsI:bsicbz2) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/README.md#L36)):*
> ```Markdown
>    sudo chown $USER /var/run/docker.sock
>    echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' |
>    sudo tee /etc/apt/sources.list.d/intel-sgx.list
> ```

Wouldn't it be better to indent this line with additional 4 spaces? Right now it looks like it's a separate command (which it is not -- it is fed the output of the previous line, through the pipe).
___
*[`Curated-Apps/README.md` line 38 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5I0ZjBXEM0EixmViV:-NL5I0ZjBXEM0EixmViW:bsicbz2) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/README.md#L38)):*
> ```Markdown
>    sudo tee /etc/apt/sources.list.d/intel-sgx.list
>    wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key |
>    sudo apt-key add -
> ```

Wouldn't it be better to indent this line with additional 4 spaces? Right now it looks like it's a separate command (which it is not -- it is fed the output of the previous line, through the pipe).
___
*[`Curated-Apps/workloads/pytorch/README.md` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5J7qbAP9GyVwPblwy:-NL5J7qbAP9GyVwPblwz:b-d0hajp) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/workloads/pytorch/README.md#L28)):*
> ```Markdown
>       ```sh
>       /bin/bash workloads/pytorch/base_image_helper/helper.sh
>       ```
> ```

I'd prefer to have an empty line before each next bullet item. Currently, in all READMEs you have it differently: sometimes there is an empty line, sometimes there is none. Could you unify?
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/README.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5IOAY1k4KFupdrqqx:-NL5IOAY1k4KFupdrqqy:b-xujnda) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/workloads/pytorch/base_image_helper/README.md#L10)):*
> ```Markdown
>   ```
> 
>   [Install gramine](https://gramine.readthedocs.io/en/latest/quickstart.html#install-gramine): File Encryption is done using `gramine-sgx-pf-crypt` tool which is part of gramine installation.
> ```

Please `gramine` -> `Gramine` (2x in this paragraph)
___
*[`Curated-Apps/workloads/redis/README.md` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5I_o5-SNb6oyXAt62:-NL5I_o5-SNb6oyXAt63:b-f5rhaz) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/workloads/redis/README.md#L20)):*
> ```Markdown
>    python3 ./curate.py redis redis:7.0.0 test
>    ```
> 3. To generate a custom confidential compute image based on a user-provided Redis image, execute
> ```

`To generate` -> `Or, to generate` ? Like you did for PyTorch

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: 1 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/README.md` line 36 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5HrzJ8-vSOWbKZLsH:-NL5Smn60E9QJgv3iqVI:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/README.md#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it be better to indent this line with additional 4 spaces? Right now it looks like it's a separate command (which it is not -- it is fed the output of the previous line, through the pipe).
</blockquote></details>

Done.
___
*[`Curated-Apps/README.md` line 38 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5I0ZjBXEM0EixmViV:-NL5Sooa5Cz8TwTnCgs7:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/README.md#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it be better to indent this line with additional 4 spaces? Right now it looks like it's a separate command (which it is not -- it is fed the output of the previous line, through the pipe).
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5J7qbAP9GyVwPblwy:-NL5SqrLAXSET4NssWdC:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/workloads/pytorch/README.md#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer to have an empty line before each next bullet item. Currently, in all READMEs you have it differently: sometimes there is an empty line, sometimes there is none. Could you unify?
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/base_image_helper/README.md` line 10 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5IOAY1k4KFupdrqqx:-NL5SrnQ6Nxxk_Et5EPo:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/workloads/pytorch/base_image_helper/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please `gramine` -> `Gramine` (2x in this paragraph)
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/redis/README.md` line 20 at r1](https://reviewable.io/reviews/gramineproject/contrib/28#-NL5I_o5-SNb6oyXAt62:-NL5Sspz2TGLBOHIFNNU:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/00930aaf64c82efdc046b334ccf1e33eadc256e4/Curated-Apps/workloads/redis/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`To generate` -> `Or, to generate` ? Like you did for PyTorch
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Curated-Apps/workloads/pytorch/README.md` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/28#-NLeVn1nACOGLUdcwvEM:-NLeVn1nACOGLUdcwvEN:b8h0w5u) ([raw file](https://github.com/gramineproject/contrib/blob/7ef086a32940e212ad771a1467a6c4bd526a6abd/Curated-Apps/workloads/pytorch/README.md#L32)):*
> ```Markdown
>       The above `helper.sh` script encrypts sensitive files such as models, data etc. with an auto
>       generated test encryption key `workloads/pytorch/base_image_helper/encryption_key` and copies
>       to the base image. Learn more about [Encrypted files](https://gramine.readthedocs.io/en/latest/manifest-syntax.html?highlight=protected#encrypted-files) support in gramine
> ```

`...in gramine` -> `...in Gramine.` (with capital letter + dot at the end)
___
*[`Curated-Apps/workloads/pytorch/README.md` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/28#-NLeVrep5UKABaAfjGLa:-NLeVrep5UKABaAfjGLb:b-588vx8) ([raw file](https://github.com/gramineproject/contrib/blob/7ef086a32940e212ad771a1467a6c4bd526a6abd/Curated-Apps/workloads/pytorch/README.md#L32)):*
> ```Markdown
>       The above `helper.sh` script encrypts sensitive files such as models, data etc. with an auto
>       generated test encryption key `workloads/pytorch/base_image_helper/encryption_key` and copies
>       to the base image. Learn more about [Encrypted files](https://gramine.readthedocs.io/en/latest/manifest-syntax.html?highlight=protected#encrypted-files) support in gramine
> ```

Please don't use `latest`, use `stable` for readthedocs

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/workloads/pytorch/README.md` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/28#-NLeVn1nACOGLUdcwvEM:-NLegN-4A27w8SjmuqjO:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/7ef086a32940e212ad771a1467a6c4bd526a6abd/Curated-Apps/workloads/pytorch/README.md#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...in gramine` -> `...in Gramine.` (with capital letter + dot at the end)
</blockquote></details>

Done.
___
*[`Curated-Apps/workloads/pytorch/README.md` line 32 at r3](https://reviewable.io/reviews/gramineproject/contrib/28#-NLeVrep5UKABaAfjGLa:-NLegNfU86dm4dln6pIp:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/7ef086a32940e212ad771a1467a6c4bd526a6abd/Curated-Apps/workloads/pytorch/README.md#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't use `latest`, use `stable` for readthedocs
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 2 at r5](https://reviewable.io/reviews/gramineproject/contrib/28#-NPRu_sC2INbWDhNLn25):*
This doesn't conform to our commit style



_Code quote:_
```
Improvements in READMEs
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
