### PR TITLE
[packaging] Add initial debian build for MAA attestation

### PR DESCRIPTION
**Pull request by woju**
This PR adds debian packaging. Currently it only builds `Integrations/azure/ra_tls_maa`. It was manually tested according to instructions in README in "Testing MAA libraries", but the install is done like this:

```sh
sudo apt-get install devscripts # if you didn't already -- this is for debuild tool
sudo apt-get build-dep .
debuild
sudo apt-get install ../gramine-ratls-maa_*_amd64.deb
```

Then patch against `CI-Examples/ra-tls-mbedtls`, `make`, and `./server` and `./client` as described.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/control` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrWOq84WN01mvAepUE:-NgrWOq84WN01mvAepUF:b-m14rls) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/control#L21)):*
> ```
>  Microsoft Azure Attestation (MAA) provider and retrieving the attestation
>  response (the JWT) from it.
>  .
> ```

Just to be sure -- this `.` line is a special syntax to separate descriptions of different files?
___
*[`debian/control` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrW_n371toDwdhAd3f:-NgrW_n371toDwdhAd3g:b-9mpm03) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/control#L28)):*
> ```
>  gramine,
>  ${misc:Depends},
>  ${shlibs:Depends},
> ```

What are these two `xxx:Depends` lines? How to decipher them?
___
*[`debian/copyright` line 27 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrWnqeCltaqjbOamT7:-NgrWnqf-OwGIJPEtVGE:b-4zdsu6) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L27)):*
> ```
> Files: Intel-Confidential-Compute-for-X/*
> Copyright: 2021-2023 Intel Corporation
> License: LGPL-3.0+
> ```

Why do we need all these files listed here? E.g., Intel Confidential Compute for X will never be a package (because it's not about packaging at all).

Can we keep only the `Integrations/azure/ra_tls_maa/*` item?
___
*[`debian/gramine-ratls-maa.triggers` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrX32b-n92DUkDcMNQ:-NgrX32b-n92DUkDcMNR:b-lr4bk) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/gramine-ratls-maa.triggers#L1)):*
> ```
> activate-noawait ldconfig
> ```

Out of curiosity, what does this do?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`debian/control` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrWOq84WN01mvAepUE:-NgrbFt59parvRAXi26B:b-23lvhk) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/control#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just to be sure -- this `.` line is a special syntax to separate descriptions of different files?
</blockquote></details>

This is because the file is parsed by RFC(2)822 (email header) parser. You're looking at an email with funny headers, parsed recursively, so that the "body" is again parsed as head+tail, like a LISP list. This way you get separate sections or "stanzas".

So the definition of the email is that headers are separated from the contents by an empty line. So you can't have empty lines within stanzas. This is not a problem for fields like names (Source/Package), list of short strings (Depends etc.), but it's a problem for long, free-form natural language descriptions. So it part of the definition of this format is that if you want an empty line, you should instead write a line with a single dot and any human-facing tool (e.g., aptitute or synaptic) is supposed to strip those dots:

https://www.debian.org/doc/debian-policy/ch-controlfields.html#description (third point and esp. this footnote: https://www.debian.org/doc/debian-policy/ch-controlfields.html#id24)

This is Good Engineering™ because the 1) format is reasonably structured, but 2) you don't need to write any custom parser, because every language already has an email parser (`python3 -c "import email.parser"`), 3) the format is universal (all debian tools use this RFC822 convention for different pieces of both metadata and config — see `apt_preferences(5)` for example) and 4) is very human-read-writeable (more than TOML for example, which BTW was unavailable in mid-90s when this was engineered). The only downside are those dots... And to a lesser extent a mandatory indent if you want to continue a "line" (header).
___
*[`debian/control` line 28 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrW_n371toDwdhAd3f:-NgreLmh5_wwowxSDRUY:bcpbz7l) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/control#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What are these two `xxx:Depends` lines? How to decipher them?
</blockquote></details>

https://manpages.debian.org/bookworm/debhelper/debhelper.7.en.html#Automatic_generation_of_miscellaneous_dependencies%2e
https://manpages.debian.org/bookworm/dpkg-dev/deb-substvars.5.en.html

Those are variables ("substvars" if you'd like to ddg this) and this is dpkg mechanism and debhelper's convention, a way of specifying various autodetected features. The convention is `${<language>:Field}`, and language-specific debhelper modules add them to a per-package set of substitutions to replace within package metadata (I think it's several different files, not only this one). Those are predominantly used for `Depends`, so that the package can automatically Depend on an autodetected other package (the one containing specific Python module, or `.so` library in this case). So those are `${python:Depends}`, `${perl:Depends}` etc. ("shlibs" can be understood as the C-specific one, for "shared libraries"). You generally don't know what's inside until you inspect the package, or you can read `debian/<package>.substvars` leftover after you build the package yourself.

They are of course documented, but there isn't an exhaustive list of those anywhere, because every language has different build processes and debian did another set of tools for every package. You need to score thought various `dh_*` manuals to check every single tool that is executed as part of the package build process. You can get a list of those tools that will run for a particular package by checking the build log (in main package we have logs in CI, `pkg-deb-` job), or here if you don't have one, run `dh --no-act build` in the root dir, so they get listed but not executed. The set of those tools depend on plugins to main debhelper tool, `dh --with`, so varies beteewen packages.
___
*[`debian/copyright` line 27 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrWnqeCltaqjbOamT7:-Ngrhib8En2os561pFF6:b-8jxfb9) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need all these files listed here? E.g., Intel Confidential Compute for X will never be a package (because it's not about packaging at all).

Can we keep only the `Integrations/azure/ra_tls_maa/*` item?
</blockquote></details>

No, because the full repo content is distributed as "source" packed in a tarball and hashed in `.dsc`, or "debian source". It's uploaded to the repo — if instead of writing `deb https://packages.gramineproject.io` you write `deb-src https://...`, you can then `apt-get source gramine` and it will give you a full source of gramine at the time of the build. Therefore they need a defined licence, and that some files aren't used as part of building the artifacts doesn't matter — source files are still being redistributed.

There's a tool called `lintian` that checks for 100% coverage of the patters here against files in the repo and it would give an error you omit some files (cf. log `pkg-deb-` job in main repo — it's currently ignored there for the sheer volume of the warnings, but I need to fix it someday).
___
*[`debian/gramine-ratls-maa.triggers` line 1 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrX32b-n92DUkDcMNQ:-NgrjEhr3MELBImMUUIk:b-f5k7dk) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/gramine-ratls-maa.triggers#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Out of curiosity, what does this do?
</blockquote></details>

It's somewhat complicated mechanism, but essentially this causes `ldconfig` tool (https://manpages.debian.org/bookworm/manpages/ldconfig.8.en.html) to be ran by `apt-get install` after this package is unpacked. `ldconfig` regenerates `/etc/ld.so.cache`, which is a mapping of SONAME -> `filepath` for the purpose of loading libraries by `ld.so` loader (runtime linker). `ld.so` does not list directories, it only relies on this map/hash/whatever binary structure, so if you don't trigger this thing and don't regenerate this cache, then if a binary is dynamically linked against libratls-maa, then the library might not get "found", despite the file being in the correct location.

In theory this should have been added automatically by one of the debhelpers (https://manpages.debian.org/bookworm/debhelper/dh_makeshlibs.1.en.html), but for some reason it wasn't. (It's unclear to me why. You know, it's a complicated mechanism). And there are some caveats, like it's not guaranteed to run for every package installed that needs it, but if `apt-get install` transaction contains several packages that triggers ldconfig, it might be ran only once, after all of them are installed — which for performance reasons is mostly what you want, but in some cases you need the dependent library to be able to run some tool as part of the install process of another. So there are knobs to tune this behaviour, and it's tightly coupled to package state resolution in APT (the other part of why this is compliated). Here those details probably don't matter.

- https://manpages.debian.org/bookworm/dpkg-dev/deb-triggers.5.en.html (short intro)
- `zless /usr/share/doc/dpkg/triggers.txt.gz` (on a Debian/Ubuntu system — long intro, motivation, and thorough explanation)
- https://manpages.debian.org/bookworm/dpkg/dpkg-trigger.1.en.html (the tools that runs it)

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`debian/control` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NgrWOq84WN01mvAepUE:-NgsHDkW4b9kuyd3Xx6v:b-tpk12p) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/control#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is because the file is parsed by RFC(2)822 (email header) parser. You're looking at an email with funny headers, parsed recursively, so that the "body" is again parsed as head+tail, like a LISP list. This way you get separate sections or "stanzas".

So the definition of the email is that headers are separated from the contents by an empty line. So you can't have empty lines within stanzas. This is not a problem for fields like names (Source/Package), list of short strings (Depends etc.), but it's a problem for long, free-form natural language descriptions. So it part of the definition of this format is that if you want an empty line, you should instead write a line with a single dot and any human-facing tool (e.g., aptitute or synaptic) is supposed to strip those dots:

https://www.debian.org/doc/debian-policy/ch-controlfields.html#description (third point and esp. this footnote: https://www.debian.org/doc/debian-policy/ch-controlfields.html#id24)

This is Good Engineering™ because the 1) format is reasonably structured, but 2) you don't need to write any custom parser, because every language already has an email parser (`python3 -c "import email.parser"`), 3) the format is universal (all debian tools use this RFC822 convention for different pieces of both metadata and config — see `apt_preferences(5)` for example) and 4) is very human-read-writeable (more than TOML for example, which BTW was unavailable in mid-90s when this was engineered). The only downside are those dots... And to a lesser extent a mandatory indent if you want to continue a "line" (header).
</blockquote></details>

Thanks for the thorough explanation

**Review by mkow — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/57#-NgzkSrPDNb7uZ3Wwxhy:-NgzkSrPDNb7uZ3Wwxhz:b-f21i5n) (no related file):*
This `debian/` should go under `Integrations/azure`, this repo is hosting multiple unrelated projects and each may have its own packaging scripts.

___

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/57#-NgzkSrPDNb7uZ3Wwxhy:-NhW3wdT0OUuvf55p5sp:b-83dli3) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This `debian/` should go under `Integrations/azure`, this repo is hosting multiple unrelated projects and each may have its own packaging scripts.
</blockquote></details>

No, there should be one `debian/` directory per repo. If we wanted to package also those other things, we can build them as part of a single `debian/` directory (there's nothing wrong with building multiple projects within single set of packaging scripts). This matches the fact that there will be a single repo and a single version tag. If we want separate packaging, we should move things to separate repositories, but since we don't, it's OK to package them from one `Source:`.

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/57#-NgzkSrPDNb7uZ3Wwxhy:-NhW77Kq-bOvfxC8QZ_g:b-q9tvym) (no related file):*
> This matches the fact that there will be a single repo and a single version tag.

This argument makes a lot of sense to me.

___

**Review by kailun-qin — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow and @woju)

___
*[`debian/copyright` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NhgB38k9VKNZh_l7_Nc:-NhgB38k9VKNZh_l7_Nd:bd0advt) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L33)):*
> ```
>  Examples/aks-python-helloworld/*
> Copyright: 2022 Intel Corporation
> License: all-rights-reserved
> ```

Why is it "all-rights-reserved"?



_Code quote:_
```
License: all-rights-reserved
```
___
*[`debian/copyright` line 53 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NhgBSy_0j4isR1uFXJ4:-NhgBSy_0j4isR1uFXJ5:boxq6jz) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L53)):*
> ```
> 
> License: all-rights-reserved
>  All rights reserved.
> ```

Is this required?



_Code quote:_
```
License: all-rights-reserved
 All rights reserved.
```

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 3 unresolved discussions (waiting on @kailun-qin and @mkow)

___
*[`debian/copyright` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NhgB38k9VKNZh_l7_Nc:-NhlYhD_6S7t4Z7Di-AP:b-9stl2o) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why is it "all-rights-reserved"?
</blockquote></details>

Because there's no explicit licence specified. Unless I've missed some obvious way, I haven't found any reliable indication, under what licence those files are.
___
*[`debian/copyright` line 53 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NhgBSy_0j4isR1uFXJ4:-NhlYzCi46p-Yah2Cw03:b-2w9bnx) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L53)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Is this required?
</blockquote></details>

Yes. There are two kind of stanzas here:
- one with `Files:`, where `License:` is a tag that refers to the second kind of stanza;
- the second kind of stanza (without `Files:`) contain the actual text of the licence, and the tag as the first line.

(there's also the third kind, header, which is not relevant here)

So `all-rights-reserved` everywhere else is a tag that refers to this stanza here.
For reference, here's specification of the format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ (cf. sections 5.1 through 5.3).

**Review by kailun-qin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`debian/copyright` line 33 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NhgB38k9VKNZh_l7_Nc:-NhyHJpY5a4ivz4QVrLM:bfzryh5) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L33)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because there's no explicit licence specified. Unless I've missed some obvious way, I haven't found any reliable indication, under what licence those files are.
</blockquote></details>

Ah, indeed...
___
*[`debian/copyright` line 53 at r1](https://reviewable.io/reviews/gramineproject/contrib/57#-NhgBSy_0j4isR1uFXJ4:-NhyHcP9Cr_FW0zNpqix:blheu7n) ([raw file](https://github.com/gramineproject/contrib/blob/cc131dcf18762c24cf8335a2d55a3c9eb3d90d63/debian/copyright#L53)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes. There are two kind of stanzas here:
- one with `Files:`, where `License:` is a tag that refers to the second kind of stanza;
- the second kind of stanza (without `Files:`) contain the actual text of the licence, and the tag as the first line.

(there's also the third kind, header, which is not relevant here)

So `all-rights-reserved` everywhere else is a tag that refers to this stanza here.
For reference, here's specification of the format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ (cf. sections 5.1 through 5.3).
</blockquote></details>

Gotcha, thanks for the explanations!

**Review by mkow — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/57)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/57#-NkV-gQL0YYUDbQGIghR:-NkV-gQM8Hb7h71LiErO:btf55q3) (no related file):*
I rebased to master and tested locally, using a fresh Ubuntu 22.04 Docker image.

1. Need to install Gramine itself first.
2. Need to additionally perform `cd Integrations/azure/ra_tls_maa/ && meson subprojects download`
3. Then can do as described in the PR description.

I'm a bit surprised that the installed package contains this file:
```bash
$ cat usr/share/lintian/overrides/gramine-ratls-maa
gramine-ratls-maa: package-name-doesnt-match-sonames
gramine-ratls-maa: shared-library-lacks-version
gramine-ratls-maa: embedded-library
gramine-ratls-maa: custom-library-search-path
```

But I guess this is good manners. Anyway, I'm fine with this PR. It's ready for merge.

___

**Pull request merged**
