### PR TITLE
[Curated-Apps] Display workload specific examples on UI

### PR DESCRIPTION
**Pull request by jkr0103**
1. Currently we display examples on curation UI for list of encrypted files for PyTorch even if workload type is not PyTorch, it's hard coded [here](https://github.com/gramineproject/contrib/blob/master/Curated-Apps/util/constants.py#L106).

2. Also examples are missing for other parameters e.g. `docker run flags`, `comman-line arguments` etc. This PR add workload specific examples on UI by reading all the parameters used in test mode.

3. Also increased the height of UI to accomodate more text on UI as well as in `user input` section.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)

### CODE REVIEW

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: 0 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Curated-Apps/curate.py` line 380 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjB7e03w0j3Hs26_a:-NRIRJaN94zJYoQfyZAh:b117p4r) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/curate.py#L380)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is the first time I see such a construct in Python. How does it work? Could you re-write it to more "classic" expressions?
</blockquote></details>

That is [assignment expression](https://peps.python.org/pep-0572/) syntax, just saw that it works on `Python3.8+` and will break curation on `Ubuntu18.04` as it's based on `Python3.6.9`, hence replaced it.
___
*[`Curated-Apps/curate.py` line 393 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjKL26wNJOD0lyMcw:-NRISo529AEBgVa2NRC-:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/curate.py#L393)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 402 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjLGX7pYLY3HdzBOU:-NRISogM8bgIwFc7mq-k:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/curate.py#L402)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/curate.py` line 411 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjLyq6yqIEAOJRwaT:-NRISp4A54FuTz5VBnN5:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/curate.py#L411)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Curated-Apps/util/constants.py` line 98 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjbd463BC6znXC1AJ:-NRIT7wV3GX_7CuOmubK:b-4nvim0) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/util/constants.py#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is there a `,` in this message? Ditto for all other places
</blockquote></details>

This is a delimeter to split the list and each list item is added in new line on curses UI. In this case We want to add the workload specific example on a new line ( also fill with color), hences added the `,`.

Code that uses it and split: https://github.com/jkr0103/contrib/blob/403b0cbdc50b9f214b82f1aa91476217779185a1/Curated-Apps/curate.py#L416
___
*[`Curated-Apps/util/constants.py` line 110 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjUY-A2OLseZRbqNZ:-NRIU8H89sgNnJ2QDYvF:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/util/constants.py#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Command-line` -> `command-line` (please lower case)
</blockquote></details>

Done.
___
*[`Curated-Apps/util/constants.py` line 119 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjhQu3vZ9jiIiUKAN:-NRIU8dC8OZdzPgEM1bZ:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/util/constants.py#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Environment` -> `environment` (please lower case)
</blockquote></details>

Done.

**Review by dimakuv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Curated-Apps/curate.py` line 380 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjB7e03w0j3Hs26_a:-NRX3IEh56j4pNfECeTM:buimp6o) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/curate.py#L380)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

That is [assignment expression](https://peps.python.org/pep-0572/) syntax, just saw that it works on `Python3.8+` and will break curation on `Ubuntu18.04` as it's based on `Python3.6.9`, hence replaced it.
</blockquote></details>

Heh, I have flashbacks of Pascal/Delphi seeing this syntax, and my brain refuses to parse such constructs.
___
*[`Curated-Apps/util/constants.py` line 98 at r1](https://reviewable.io/reviews/gramineproject/contrib/42#-NRHjbd463BC6znXC1AJ:-NRX3vQFBE4PfPIVskIs:bs0u3t8) ([raw file](https://github.com/gramineproject/contrib/blob/71d9310936a07212061b27e8d01dfc3b3729c450/Curated-Apps/util/constants.py#L98)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

This is a delimeter to split the list and each list item is added in new line on curses UI. In this case We want to add the workload specific example on a new line ( also fill with color), hences added the `,`.

Code that uses it and split: https://github.com/jkr0103/contrib/blob/403b0cbdc50b9f214b82f1aa91476217779185a1/Curated-Apps/curate.py#L416


</blockquote></details>

Oh, that's a bit unintuitive. Ok, got it.

**Comment by jkr0103** [comment]
PR was showing other comments from master due to this github bug https://github.com/orgs/community/discussions/51948

Fixed it by squashing both the commits on the PR

**Review by dimakuv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOl41Aog4YWJejTq0:-NYSUoWzErwWA_tMr2Mn:b-itt21p) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

If you see in PR description, I mentioned three points but first two are related and cannot be separated. Last one is for increasing the UI  and input text box size which is upto 20 lines from start in `constants.py`. I think that's small change, hence I kept these changes in single PR. Let me know if you still want me to split it into two PRs.
</blockquote></details>

Still, could you please separate into smaller PRs? Maybe just two PRs is enough.

___
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 382 at r7](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOCfQ7bHZKIT_iVYK:-NYSV0HK3ze5DIxMkYoI:b-udaruc) ([raw file](https://github.com/gramineproject/contrib/blob/b67de96a19d33d79ff884063bc8cf2800343434b/Intel-Confidential-Compute-for-X/curate.py#L382)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

This is `list slicing` in python and is considered a common practice in Python.
Syntax here inserts the workload specific example in the list and we need a list here due to UI constraints.
</blockquote></details>

But why do you insert at index 5 exactly?

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: 61 of 69 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOl41Aog4YWJejTq0:-N_csjBa-7tG6-qJOgAC:bnva4nb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still, could you please separate into smaller PRs? Maybe just two PRs is enough.
</blockquote></details>

Done, will create separate PR for UI size changes

___
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 382 at r7](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOCfQ7bHZKIT_iVYK:-N_csq6K6UwJ1fxNjvD9:b-uzye9r) ([raw file](https://github.com/gramineproject/contrib/blob/b67de96a19d33d79ff884063bc8cf2800343434b/Intel-Confidential-Compute-for-X/curate.py#L382)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why do you insert at index 5 exactly?
</blockquote></details>

We want to insert just before `Press CTRL+G when done` which is 6th item in the list here (list items are `,` comma separated) https://github.com/jkr0103/contrib/blob/42e45970ab854be41c1385d2e55ee75b3c483eaf/Intel-Confidential-Compute-for-X/util/constants.py#L105

same for other cases as well.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOl41Aog4YWJejTq0:-N_cvGrxEQzuzGLkIKm1:b-6x4i6d) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done, will create separate PR for UI size changes
</blockquote></details>

I'll keep this blocking until you'll create a PR. Just as a reminder.

___
___
*[`Intel-Confidential-Compute-for-X/curate.py` line 382 at r7](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOCfQ7bHZKIT_iVYK:-N_cvT4zCXF06SgK15li:b-rs5iwf) ([raw file](https://github.com/gramineproject/contrib/blob/b67de96a19d33d79ff884063bc8cf2800343434b/Intel-Confidential-Compute-for-X/curate.py#L382)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We want to insert just before `Press CTRL+G when done` which is 6th item in the list here (list items are `,` comma separated) https://github.com/jkr0103/contrib/blob/42e45970ab854be41c1385d2e55ee75b3c483eaf/Intel-Confidential-Compute-for-X/util/constants.py#L105

same for other cases as well.
</blockquote></details>

Oouf. Ok, I don't care much.

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/contrib/42#-NVUOl41Aog4YWJejTq0:-N_cx0qC6quMrNsjWMc5:by4arga) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll keep this blocking until you'll create a PR. Just as a reminder.
</blockquote></details>

Created PR https://github.com/gramineproject/contrib/pull/51

___

**Review by dimakuv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 2 of 69 files at r5, 1 of 2 files at r6, 58 of 65 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

**Review by dimakuv — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
