### PR TITLE
[Curated-apps] README updates

### PR DESCRIPTION
**Pull request by jkr0103**
README updates and removed references for Ubuntu 18.04.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/workloads/mysql/README.md` line 121 at r1](https://reviewable.io/reviews/gramineproject/contrib/77#-NqlJ9Wf81XHDIbkl439:-NqlJ9Wf81XHDIbkl43A:b9fhvm8) ([raw file](https://github.com/gramineproject/contrib/blob/4e4849c07ee7cfa2265a5215298264070f52ded8/Intel-Confidential-Compute-for-X/workloads/mysql/README.md#L121)):*
> ```Markdown
>     |                                         running the test MySQL image.
>     |-- insecure_args.txt                   # This file contains command line arguments required
>     |                                         for running the test MySQL image.
> ```

Please indent these three items correctly (two spaces to the left)
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 57 at r1](https://reviewable.io/reviews/gramineproject/contrib/77#-NqlJ3737FSQbaWzZvnV:-NqlJ3742raMUtlr2HGk:b-i1jhmj) ([raw file](https://github.com/gramineproject/contrib/blob/4e4849c07ee7cfa2265a5215298264070f52ded8/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L57)):*
> ```Markdown
>     |                                        GSC.
>     |-- common_args.txt                    # This file contains command line arguments required for
>     |                                        running the Redis image.
> ```

Please add a newline

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/workloads/mysql/README.md` line 121 at r1](https://reviewable.io/reviews/gramineproject/contrib/77#-NqlJ9Wf81XHDIbkl439:-NqlbyHv4uUouxIp04Qb:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4e4849c07ee7cfa2265a5215298264070f52ded8/Intel-Confidential-Compute-for-X/workloads/mysql/README.md#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please indent these three items correctly (two spaces to the left)
</blockquote></details>

Done.
___
*[`Intel-Confidential-Compute-for-X/workloads/redis/README.md` line 57 at r1](https://reviewable.io/reviews/gramineproject/contrib/77#-NqlJ3737FSQbaWzZvnV:-Nqlbyjv44M3wo3gbeh_:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/4e4849c07ee7cfa2265a5215298264070f52ded8/Intel-Confidential-Compute-for-X/workloads/redis/README.md#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a newline
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/gramineproject/contrib/77#-NqtMcFfDka93WRu2Tl0):*
Missing verb



_Code quote:_
```
README updates
```

**Review by kailun-qin — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

**Review by mkow — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/77)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
