### PR TITLE
[Curated-Apps] Increase TUI size to accomodate more text and user input

### PR DESCRIPTION
**Pull request by jkr0103**
We have more text on Curated-Apps TUI as we are going to displaying workload specific input examples, hence need to increate the UI size and text box size for user inputs as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/51#-N_cxBWt71THIpf-Abp9:-N_cxBWt71THIpf-AbpA:bmzbb1o) ([raw file](https://github.com/gramineproject/contrib/blob/8c05f10991bcf4dd758fdfb749735c8415b66cff/Intel-Confidential-Compute-for-X/util/constants.py#L21)):*
> ```Python
> partition_width = 1
> partition_y = 5
> partition_height = screen_height - (user_input_height + partition_y + 1)
> ```

You removed one variable called `guide_win_height` and added a new variable called `partition_height`. But there are no other changes in this PR (removing the old variable usages and adding the new variable usages). How does it work? Or are these some UI-framework specific names of variables?

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 21 at r1](https://reviewable.io/reviews/gramineproject/contrib/51#-N_cxBWt71THIpf-Abp9:-N_d5dwOEmXVLbXbw27m:b-4w4cqr) ([raw file](https://github.com/gramineproject/contrib/blob/8c05f10991bcf4dd758fdfb749735c8415b66cff/Intel-Confidential-Compute-for-X/util/constants.py#L21)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Details about the changes in the PR:

- `partition_height` was constant but now it's calculated based on other parameters
- `guide_win_height` was already initialized two line above, hence removed
- `screen_height` is increased from 35 to 46
- `user_input_height` is increased from 5 to 6
- We have two partitions on UI, that partition is also adjusted.

That's all this PR is intended for.
</blockquote></details>

Ok, thanks. I totally didn't notice the `guide_win_height` assignment.
___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 14 at r2](https://reviewable.io/reviews/gramineproject/contrib/51#-N_d5a4oB4HvMouDU8NV:-N_d5a4oB4HvMouDU8NW:bn0u3tk) ([raw file](https://github.com/gramineproject/contrib/blob/5326d3e8b9f01ad08ed720b521a4b11d5cbfa966/Intel-Confidential-Compute-for-X/util/constants.py#L14)):*
> ```Python
> title_width = screen_width
> sub_title_width = title_width / num_sub_titles
> user_console_height = guide_win_height = screen_height - user_input_height - title_height
> ```

Ouch, this is very obscure. Can you split into two lines?

**Review by jkr0103 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Intel-Confidential-Compute-for-X/util/constants.py` line 14 at r2](https://reviewable.io/reviews/gramineproject/contrib/51#-N_d5a4oB4HvMouDU8NV:-N_guvcpE9smAmXnsstO:b-896fix) ([raw file](https://github.com/gramineproject/contrib/blob/5326d3e8b9f01ad08ed720b521a4b11d5cbfa966/Intel-Confidential-Compute-for-X/util/constants.py#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ouch, this is very obscure. Can you split into two lines?
</blockquote></details>

Done.

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/51#-Na5tb60-NcjlMFqZLrh):*




_Suggestion:_
```
accommodate
```

**Review by dimakuv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/gramineproject/contrib/51#-Na5tb60-NcjlMFqZLrh):*
Done

**Review by mkow — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/51)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
