### PR TITLE
[packaging] Add packaging for ITA

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/gramineproject/contrib/79)

### CODE REVIEW

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/79)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/control` line 34 at r1](https://reviewable.io/reviews/gramineproject/contrib/79#-NrB_19278EeUTClwxzI:-NrB_19278EeUTClwxzJ:b4s3jfc) ([raw file](https://github.com/gramineproject/contrib/blob/3290fe4f63f42ad65a1e5fe8768e94b4abe8b46b/debian/control#L34)):*
> ```
> Architecture: amd64
> Description: Intel Trust Authority (ITA) verifier for RA-TLS
>  TBD
> ```

Why not steal the description from `gramine-ratls-maa`? That's like exactly the same.

**Review by dimakuv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/79)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[`debian/copyright` line 27 at r2](https://reviewable.io/reviews/gramineproject/contrib/79#-NrLBUUFEfvBvionzMj4:-NrLBUUFEfvBvionzMj5:bazorrw) ([raw file](https://github.com/gramineproject/contrib/blob/8d76d620171692bbd6eea185e21965320008f81e/debian/copyright#L27)):*
> ```
> Files: Integrations/intel/ra_tls_ita/*
> Copyright: 2024 Intel Corporation
> License: LGPL-3.0+
> ```

This is the only file where you still have a different order (first MAA, then ITA). Do you want to fix?

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/79)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`debian/copyright` line 27 at r2](https://reviewable.io/reviews/gramineproject/contrib/79#-NrLBUUFEfvBvionzMj4:-Nrf8Nkf2gGaovKXaTXb:b-r9ew3f) ([raw file](https://github.com/gramineproject/contrib/blob/8d76d620171692bbd6eea185e21965320008f81e/debian/copyright#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is the only file where you still have a different order (first MAA, then ITA). Do you want to fix?
</blockquote></details>

I do want.

**Review by dimakuv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/contrib/79)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
